{{-- Privacy Policy — English (NUBL) --}}
<section>
    <h2>1. Introduction</h2>
    <p>
        NUBL is committed to protecting users’ privacy and the confidentiality of their personal information, and processes data in accordance with applicable laws and regulations in the Kingdom of Saudi Arabia, and in a manner consistent with the nature of the services the platform provides to beneficiaries, providers, donors, and administration.
    </p>
    <p>
        By using the platform, you acknowledge that you have read this policy and agree to its contents.
    </p>
</section>

<section>
    <h2>2. Data we may collect</h2>
    <p>The platform may collect the following data depending on the user type and service used:</p>

    <h3>A. Data you provide directly</h3>
    <ul>
        <li>Full name</li>
        <li>National ID number or related verification data</li>
        <li>Mobile number</li>
        <li>Email address</li>
        <li>City or general location information</li>
        <li>Account data and usage preferences</li>
        <li>Request, donation, or service-related data</li>
        <li>Documents, attachments, or proofs you submit</li>
        <li>Messages, notes, or requests sent through the platform</li>
    </ul>

    <h3>B. Data generated by platform use</h3>
    <ul>
        <li>IP address</li>
        <li>Browser type, operating system, and device</li>
        <li>Login date and time</li>
        <li>Pages or screens accessed</li>
        <li>Service interaction logs</li>
        <li>Technical identifiers and cookies, where used</li>
    </ul>

    <h3>C. Operational service-related data</h3>
    <ul>
        <li>Request status and lifecycle within the platform</li>
        <li>Verification, receipt, or completion logs</li>
        <li>Payment or donation records, where applicable</li>
        <li>Audit, security, and system activity logs</li>
    </ul>
</section>

<section>
    <h2>3. Purposes of collection</h2>
    <p>Data is collected and used for the following purposes:</p>
    <ul>
        <li>Creating accounts and managing access and permissions</li>
        <li>Providing digital services and operating the platform</li>
        <li>Receiving, reviewing, approving, and tracking requests</li>
        <li>Managing donations, contributions, or related transactions</li>
        <li>Verifying identity, eligibility, and correctness of procedures</li>
        <li>Enabling verification of receipt, execution, or completion</li>
        <li>Communicating with users and notifying them of request or process status</li>
        <li>Improving performance, user experience, and service development</li>
        <li>Protecting the platform from fraud, misuse, or unauthorized access</li>
        <li>Complying with legal and regulatory requirements</li>
        <li>Preparing operational or statistical reports in a manner that does not undermine personal data confidentiality</li>
    </ul>
</section>

<section>
    <h2>4. Legal basis for processing</h2>
    <p>Processing may rely on one or more of the following bases:</p>
    <ul>
        <li>Data subject consent, where required</li>
        <li>Performance of a contract or provision of a requested service</li>
        <li>Compliance with a legal or regulatory obligation</li>
        <li>Legitimate interests of the platform that do not override data subject rights</li>
        <li>Protecting the platform or users from fraud, misuse, or security risks</li>
    </ul>
</section>

<section>
    <h2>5. Sharing and disclosure</h2>
    <p>
        Personal data is not sold. However, data may be disclosed or shared to the extent necessary with:
    </p>
    <ul>
        <li>Legally authorized entities</li>
        <li>Technical or operational partners involved in delivering the service</li>
        <li>Payment, verification, hosting, notification, or technical support providers</li>
        <li>Entities relevant to executing a request, donation, or in-platform procedure</li>
        <li>Entities that applicable law or competent decisions require to receive data</li>
    </ul>
    <p>
        This is done on a need-to-know basis aligned with legitimate purposes, with appropriate measures to protect confidentiality.
    </p>
</section>

<section>
    <h2>6. Storage and retention</h2>
    <p>
        The platform retains personal data and operational logs for as long as necessary to achieve the purposes described in this policy, or for periods required by laws, regulatory procedures, protection and audit requirements, or dispute resolution, after which data is destroyed or anonymized in accordance with applicable laws and approved procedures.
    </p>
</section>

<section>
    <h2>7. Data protection and information security</h2>
    <p>
        The platform implements appropriate technical and organizational measures to protect data against loss, unauthorized access, alteration, disclosure, or destruction, including:
    </p>
    <ul>
        <li>Access and permission controls</li>
        <li>Encryption or other appropriate technical safeguards where needed</li>
        <li>Activity and log monitoring</li>
        <li>Backups and business continuity measures</li>
        <li>Security controls for systems and servers</li>
    </ul>
    <p>
        However, 100% protection cannot be guaranteed in any electronic environment, and you acknowledge this while the platform commits to reasonable care.
    </p>
</section>

<section>
    <h2>8. Cookies and similar technologies</h2>
    <p>
        The platform may use cookies or similar technologies to improve performance, personalize experience, understand usage patterns, and facilitate login or preference storage. You may adjust browser settings to control these files; some platform features may be affected as a result.
    </p>
</section>

<section>
    <h2>9. Transfer and processing</h2>
    <p>
        Data may be processed, hosted, or backed up through providers or technical infrastructure inside or outside the Kingdom, depending on operational needs and in accordance with applicable laws and controls, with measures taken to maintain an appropriate level of protection.
    </p>
</section>

<section>
    <h2>10. Data subject rights</h2>
    <p>Under applicable laws, a data subject may have rights including:</p>
    <ul>
        <li>The right to be informed about how data is collected, the basis, and the purpose</li>
        <li>The right to access personal data</li>
        <li>The right to request correction of inaccurate or incomplete data</li>
        <li>The right to request destruction when retention is no longer legally or legitimately required</li>
        <li>The right to withdraw consent where processing is consent-based, without affecting the lawfulness of prior processing</li>
        <li>Any other rights provided by applicable laws and regulations</li>
    </ul>
    <p>
        Requests related to these rights are handled through the platform’s approved procedures and channels, subject to legal, security, or third-party legitimate requirements.
    </p>
</section>

<section>
    <h2>11. Operational logs and confidentiality</h2>
    <p>
        The platform may retain operational, security, and audit logs related to service use, including logs associated with requests, donations, verification, execution, login, modification, or completion, for protection, compliance, documentation, improvement, and preventing misuse.
    </p>
    <p>
        These logs are treated as confidential information and are accessed or disclosed only to the extent required for operational, legal, or security needs.
    </p>
</section>

<section>
    <h2>12. Policy changes</h2>
    <p>
        The platform may amend or update this policy at any time. The updated version becomes effective from the date it is published on the platform unless stated otherwise. Continued use after publication constitutes acceptance of the updated policy.
    </p>
</section>

<section>
    <h2>13. Contact</h2>
    <p>
        For any inquiry or request related to privacy, personal data, or information confidentiality, please contact us through the official channels approved on the platform.
    </p>
</section>
